### ISSUE TITLE
Files are not refactored and can't be compiled

### ISSUE THREAD

**Issue by notepraiya** [miatheunistudent/uni-flutter-app#5]
look like the project name was changed and a lot of files are not refactored then the project can't be compiled

**Comment by miatheunistudent** [comment]
Should be working now, can you tell me?

**Comment by notepraiya** [comment]
still don't compile, may be cuz importing libs in pubspec

**Comment by miatheunistudent** [comment]
Weird, it worked for me yesterday. I'll take a look.
